### ISSUE TITLE
Desired background?

### ISSUE THREAD

**Issue by tmcw** [Tjatse/ansi-html#2]
The default colors in ansi-html include both pure black and pure white and many colors at the edges of the spectrum, which makes it quite difficult to make text readable against a background.

For instance:

<img width="279" alt="2015-11-20 at 12 17 pm" src="https://cloud.githubusercontent.com/assets/32314/11306568/bfef03e2-8f80-11e5-8897-d25a99324130.png">

Super bright cyan

<img width="218" alt="2015-11-20 at 12 18 pm" src="https://cloud.githubusercontent.com/assets/32314/11306586/d354bb8e-8f80-11e5-86db-8e6fb986fda4.png">

Black text not visible.

Could the theme be customized, or set to something more centered on one side of the spectrum?

**Comment by Tjatse** [comment]
How about [`setColors`](https://github.com/Tjatse/ansi-html#set-colors)?

**Comment by tmcw** [comment]
:+1: setColors works great. Thanks!
