### ISSUE TITLE
0.0.7 is Vulnerable 

### ISSUE THREAD

**Issue by infa-mseelam** [Tjatse/ansi-html#21]
Recently github scan shows that version 0.0.7 is Vulnerable.

This affects all versions of package ansi-html. If an attacker provides a malicious string, it will get stuck processing the input for an extremely long time.

Any plans to fix the Vulnerability?

**Comment by ellisio** [comment]
Link to the actual advisory: https://github.com/advisories/GHSA-whgm-jr23-g3j9

**Comment by mahdyar** [comment]
This package is not being maintained anymore(apparently), alternatively, you can use the fixed version: [`ansi-html-community`](https://www.npmjs.com/package/ansi-html-community).

**Comment by TheDiveO** [comment]
@mahdyar how in case of indirect dependencies?

**Comment by jdehorty** [comment]
> @mahdyar how in case of indirect dependencies?

For indirect dependencies, to fix using `npm-force-resolutions` use the following:

https://stackoverflow.com/a/69591894/12649786

**Comment by TheDiveO** [comment]
Since this also is an issue with React-based applications where yarn is used: can you please document here how to handle the situation in case of yarn? Thank you very much!

**Comment by Tjatse** [comment]
> 

Hi @TheDiveO could you please try v0.0.9, just removed lodash from dev dependencies, and fixed the Regular Expression Denial of Service (ReDoS) in lodash
